spring.application.name=ManagerApplication

#config database
##
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mysql://localhost:3306/managerapplication?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=Asia/Ho_Chi_Minh&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=M123456
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql=true
##

#config base URL
##
managerapplication.base-url=http://localhost:8080
##
#

##config jwt

managerapplication.jwt.base64-secret="WcyC8cwnOBEgqPiFPocfwz0f6S4NH1SKe6aX79IFwmlVyQ0vGIeQKDk3padQgj61EtSupnU2Jrf9VzGkm9g8/Q=="
managerapplication.jwt.access-token-validity-in-seconds=8640000
managerapplication.jwt.refresh-token-validity-in-seconds=8640000

##


##config mail otp
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=ticketscinemasupport@gmail.com
spring.mail.password=asyvpgbxjkujdzzv

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

##